### PR TITLE
fix: credential expiration for @aws-sdk/client-s3 v3.624.0 and greater

### LINKED ISSUE #200: e2e tests: `identity.expiration.getTime` is not a function
## Description

This error was introduced today in the `@aws-sdk/client-s3@3.624.0` [release](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.624.0).
```
'    TypeError: identity.expiration.getTime is not a function\n' +
    '        at /home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/node_modules/@smithy/core/dist-cjs/index.js:272:154\n' +
    '        at /home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/node_modules/@smithy/core/dist-cjs/index.js:317:9\n' +
    '        at /home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/node_modules/@smithy/core/dist-cjs/index.js:82:17\n' +
    '        at /home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14\n' +
    '        at /home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22\n' +
    '        at RemoteStorage.folderExists (/home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/lib/remote-storage.js:91:27)\n' +
    '        at deployWeb (/home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/src/deploy-web.js:36:18)\n' +
    '        at Object.<anonymous> (/home/runner/work/aio-e2e-tests/aio-e2e-tests/.repos/aio-lib-web/e2e/e2e.js:86:13)\n' +
    '\n' +
```

## Repro

- in folder `e2e`, fill in the `.env` with the right credentials (see .env.sample)
- in the root of the repo, run `npm run e2e`

## Interim Fix

- Pin `@aws-sdk/client-s3` to `v3.623.0`.

## Final Fix

1. wherever we have credentials.expiration, convert it to a Date object:
`new Date(credentials.expiration)`. The `credentials.expiration` value is an ISO-8601 string
2. remove the pin, use `^`

### PR DESCRIPTION
**Pull request by shazron**
fixes #200

## How Has This Been Tested?

- npm run e2e

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: lib/remote-storage.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ module.exports = class RemoteStorage {
       accessKeyId: creds.accessKeyId,
       secretAccessKey: creds.secretAccessKey,
       sessionToken: creds.sessionToken,
-      expiration: creds.expiration
+      expiration: creds.expiration ? new Date(creds.expiration) : undefined
```
Comment (moritzraho) [inline lib/remote-storage.js:70]: the expiration should always be defined, but I think this is a good extra safeguard, `undefined` works with the aws-sdk right?

**Review by moritzraho — APPROVED** [review]

File: lib/remote-storage.js (hunk 1 above)
Comment (shazron) [reply lib/remote-storage.js:70]: I had to add this because of a test that didn't set the expiration
new Date(undefined) results in a NaN actually

**Review by MichaelGoberling — APPROVED** [review]
